name: Python Tests

on:
  push:
    branches: [ main, python_conversion ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.10'
        activate-environment: ANC
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        conda env update --file conda_environment.yml --name ANC
        pip install -e ./python
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        cd python
        pytest test/